import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import { replies } from '@/data';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  // const [reply, setReply] = useState('Ask a Question!')
  const [answeredQuestions, setAnsweredQuestions] = useState([]);

  function questionAskedHandler(event) {
    event.preventDefault();

    const randomReply = replies[Math.floor(Math.random() * replies.length)];

    const answeredQuestion = {
      question: event.target.question.value,
      reply: randomReply,
      id: answeredQuestions.length,
    };

    // alert(event.target.question.value)
    // alert(randomReply)
    // setReply(randomReply)
    setAnsweredQuestions([...answeredQuestions, answeredQuestion]);
  }

  function getLatestReply() {
    if (answeredQuestions.length === 0) {
      return 'Ask A Question!';
    }
    return answeredQuestions[answeredQuestions.length - 1].reply;
  }

  return (
    <>
      <Head>
        <title>Cookie Stand Admin Version 1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="text-3xl text text-black bg-emerald-500">
        Cookie Stand Admin
      </header>
      <main className="bg-white p-6 mx-auto max-w-screen-sm">
        <form
          className="flex flex-col mt-4 mb-4 bg-emerald-400"
          onSubmit={questionAskedHandler}
        >
          <p className="relative flex items-center justify-center text-black bg-emerald-400 bg-origin-padding font-bold">
            Create Cookie Stand
          </p>
          <div>
            <p className="text-black">Location</p>
            <input name="location" />
          </div>
          <table className="text-black">
            <thead>
              <tr>
                <th className="">Minimum Customers per Hour</th>
                <th className="">Maximum ustomers per Hour</th>
                <th className="">Average Cookies per Sale</th>
              </tr>
            </thead>
            <tbody>
              {/* <tr>
                        <td className = 'pl-2 border border-gray-700'>{answeredQuestions.id}</td>
                        <td className = 'pl-2 border border-gray-700'>{answeredQuestions.questions}</td>
                        <td className = 'pl-2 border border-gray-700'>{answeredQuestions.reply}</td>
                      </tr> */}
              {/* {answeredQuestions.map((question) => {
                return ( */}
              <tr>
                <td className="pl-2 border">
                  <input></input>
                </td>
                <td className="pl-2 border">
                  <input></input>
                </td>
                <td className="pl-2 border">
                  <input></input>
                </td>
                <button className="px-2 py-1 bg-emerald-600 text-black">
                  Create
                </button>
              </tr>

              {/* );
              })} */}
            </tbody>
          </table>
          
        </form>

        <p className="relative flex items-center justify-center text-black">
          Report Table Coming Soon...
        </p>
      </main>
      {/* <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main> */}
      <footer className="text-black bg-emerald-500">
        <h1>©2021</h1>
      </footer>
    </>
  );
}
